package sk.upjs.ics.traveltracker_paz1c;

public class PrimarnyMainForm extends javax.swing.JFrame {

  
    public PrimarnyMainForm() {
        initComponents();
        pridatComboBox.addItem("Kultúrne podujatia");
        pridatComboBox.addItem("Pamiatky a zaujímavosti");
        pridatComboBox.addItem("Turistika");
        pridatComboBox.addItem("Viacdňový výlet");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        najblizsieUdalostiLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        najblizsieUdalostiList = new javax.swing.JList();
        travelTrackerLabel = new javax.swing.JLabel();
        pridatComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        najblizsieUdalostiLabel.setText("Najbližšie udalosti:");

        jScrollPane1.setViewportView(najblizsieUdalostiList);

        travelTrackerLabel.setText("Travel Tracker");

        pridatComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pridať" }));
        pridatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(najblizsieUdalostiLabel)
                                .addGap(54, 54, 54)
                                .addComponent(pridatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(travelTrackerLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(travelTrackerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(najblizsieUdalostiLabel)
                    .addComponent(pridatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatComboBoxActionPerformed
        String vyber = (String) pridatComboBox.getSelectedItem();
        KulturnePodujatieForm sekundaryMainForm = new KulturnePodujatieForm((this), true, vyber);
        if ("Kultúrne podujatia".equals(vyber)){
            KulturnePodujatieForm kulturnePodujatie = new KulturnePodujatieForm(this, true);
            kulturnePodujatie.setVisible(true);
        }
        if ("Pamiatky a zaujímavosti".equals(vyber)){
            PamiatkaForm pamiatka = new PamiatkaForm(this,true);
            pamiatka.setVisible(true);
        }
        if ("Turistika".equals(vyber)){
            TuristikaForm turistika = new TuristikaForm(this, true);
            turistika.setVisible(true);
            
        }
        if ("Viacdňový výlet".equals(vyber)){
            ViacdnovyVyletForm viacdnovyVylet = new ViacdnovyVyletForm(this, true);
            viacdnovyVylet.setVisible(true);
          
        }
    }//GEN-LAST:event_pridatComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimarnyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimarnyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimarnyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimarnyMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimarnyMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel najblizsieUdalostiLabel;
    private javax.swing.JList najblizsieUdalostiList;
    private javax.swing.JComboBox pridatComboBox;
    private javax.swing.JLabel travelTrackerLabel;
    // End of variables declaration//GEN-END:variables
}
