/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.traveltracker_paz1c;

import java.text.SimpleDateFormat;

/**
 *
 * @author Robert Link
 */
public class ZobrazitPamiatkaForm extends javax.swing.JDialog {

     private Pamiatka pamiatka = new Pamiatka();
     private SimpleDateFormat dateFormat = new SimpleDateFormat("d.M.yyyy");
     
    public ZobrazitPamiatkaForm(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
         public ZobrazitPamiatkaForm(javax.swing.JDialog parent, boolean modal,Pamiatka pamiatka) {
         super(parent, modal);
         initComponents();  
         setLocationRelativeTo(null);
         this.pamiatka=pamiatka;
         refresh();
 
}
       
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datumLabel = new javax.swing.JLabel();
        ZobrazDatumlabel = new javax.swing.JLabel();
        MestoLabel = new javax.swing.JLabel();
        ZobrazMestoLabel = new javax.swing.JLabel();
        KrajinaLabel1 = new javax.swing.JLabel();
        ZobrazKrajinaLabel = new javax.swing.JLabel();
        pamiatkaLabel = new javax.swing.JLabel();
        ZobrazPamiatkaLabel = new javax.swing.JLabel();
        hodinyLabel = new javax.swing.JLabel();
        ZobrazHodinyLabel = new javax.swing.JLabel();
        VstupneLabel = new javax.swing.JLabel();
        ZobrazVstupneLabel = new javax.swing.JLabel();
        HodnotenieLabel = new javax.swing.JLabel();
        ZobrazHodnotenieLabel = new javax.swing.JLabel();
        PoznámkyiLabel = new javax.swing.JLabel();
        ZobrazPoznámkyLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        upravitButton = new javax.swing.JButton();
        NavstiveneLabel = new javax.swing.JLabel();
        ZobrazNavstiveneLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        datumLabel.setText("Dátum:");

        ZobrazDatumlabel.setText("nepoznačené");

        MestoLabel.setText("Mesto:");

        ZobrazMestoLabel.setText("nepoznačené");

        KrajinaLabel1.setText("Krajina:");

        ZobrazKrajinaLabel.setText("nepoznačené");

        pamiatkaLabel.setText("Pamiatka:");

        ZobrazPamiatkaLabel.setText("nepoznačené");

        hodinyLabel.setText("Otváracie hodiny:");

        ZobrazHodinyLabel.setText("nepoznačené");

        VstupneLabel.setText("Vstupné:");

        ZobrazVstupneLabel.setText("nepoznačené");

        HodnotenieLabel.setText("Hodnotenie:");

        ZobrazHodnotenieLabel.setText("nepoznačené");

        PoznámkyiLabel.setText("Poznámky:");

        ZobrazPoznámkyLabel.setText("nepoznačené");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        upravitButton.setText("Upraviť");
        upravitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravitButtonActionPerformed(evt);
            }
        });

        NavstiveneLabel.setText("Navštívené:");

        ZobrazNavstiveneLabel.setText("nie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KrajinaLabel1)
                            .addComponent(MestoLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZobrazMestoLabel)
                            .addComponent(ZobrazKrajinaLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pamiatkaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZobrazDatumlabel)
                            .addComponent(ZobrazPamiatkaLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NavstiveneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ZobrazNavstiveneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(29, 29, 29)
                        .addComponent(upravitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PoznámkyiLabel)
                        .addGap(52, 52, 52)
                        .addComponent(ZobrazPoznámkyLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(HodnotenieLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZobrazHodnotenieLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hodinyLabel)
                                .addComponent(VstupneLabel))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ZobrazHodinyLabel)
                                .addComponent(ZobrazVstupneLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(KrajinaLabel1)
                            .addComponent(ZobrazKrajinaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MestoLabel)
                            .addComponent(ZobrazMestoLabel))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pamiatkaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZobrazPamiatkaLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hodinyLabel)
                            .addComponent(ZobrazHodinyLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(VstupneLabel)
                            .addComponent(ZobrazVstupneLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HodnotenieLabel)
                            .addComponent(ZobrazHodnotenieLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PoznámkyiLabel)
                            .addComponent(ZobrazPoznámkyLabel)
                            .addComponent(ZobrazDatumlabel)
                            .addComponent(datumLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NavstiveneLabel)
                    .addComponent(ZobrazNavstiveneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(upravitButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void upravitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravitButtonActionPerformed
        UpravitPamiatkaForm upravitPamiatka = new UpravitPamiatkaForm(this, true, pamiatka);
        upravitPamiatka.setVisible(true);
        refresh();
    }//GEN-LAST:event_upravitButtonActionPerformed
     
     private void refresh() {
        if(pamiatka.getKrajina()!=null){
        ZobrazKrajinaLabel.setText(pamiatka.getKrajina());
        }
        
        if(pamiatka.getMesto()!=null){
        ZobrazMestoLabel.setText(pamiatka.getMesto());
        }
        
        if(pamiatka.getPamiatka_zaujimavost()!=null){
        ZobrazPamiatkaLabel.setText(pamiatka.getPamiatka_zaujimavost());
        }
        
        if(pamiatka.getDatum() !=null){
        ZobrazDatumlabel.setText(dateFormat.format(pamiatka.getDatum()));
        }

        ZobrazHodnotenieLabel.setText(Integer.toString(pamiatka.getHodnotenie()));

        if(pamiatka.getOtvaracieHodiny()!=null){
        ZobrazHodinyLabel.setText(pamiatka.getOtvaracieHodiny());
        }

        ZobrazVstupneLabel.setText(Double.toString(pamiatka.getVstupne()));

        
        
        if(pamiatka.getPodrobnosti()!=null){
        ZobrazPoznámkyLabel.setText(pamiatka.getPodrobnosti());
        }
        if(pamiatka.isNavstivene()){
        ZobrazNavstiveneLabel.setText("áno");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPamiatkaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPamiatkaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPamiatkaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPamiatkaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZobrazitPamiatkaForm dialog = new ZobrazitPamiatkaForm(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HodnotenieLabel;
    private javax.swing.JLabel KrajinaLabel1;
    private javax.swing.JLabel MestoLabel;
    private javax.swing.JLabel NavstiveneLabel;
    private javax.swing.JLabel PoznámkyiLabel;
    private javax.swing.JLabel VstupneLabel;
    private javax.swing.JLabel ZobrazDatumlabel;
    private javax.swing.JLabel ZobrazHodinyLabel;
    private javax.swing.JLabel ZobrazHodnotenieLabel;
    private javax.swing.JLabel ZobrazKrajinaLabel;
    private javax.swing.JLabel ZobrazMestoLabel;
    private javax.swing.JLabel ZobrazNavstiveneLabel;
    private javax.swing.JLabel ZobrazPamiatkaLabel;
    private javax.swing.JLabel ZobrazPoznámkyLabel;
    private javax.swing.JLabel ZobrazVstupneLabel;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JLabel hodinyLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel pamiatkaLabel;
    private javax.swing.JButton upravitButton;
    // End of variables declaration//GEN-END:variables

   
}
