
package sk.upjs.ics.traveltracker_paz1c;


public class ZobrazitTuristika extends javax.swing.JFrame {

    Turistika tura = new Turistika();
    
    public ZobrazitTuristika() {
        initComponents();
    }
     public ZobrazitTuristika(Turistika tura) {
        initComponents();
        this.tura=tura;
        if(this.tura.getKrajina()!=null){
         ZobrazKrajinalabel.setText(this.tura.getKrajina());
       }
        if(this.tura.getCiel()!=null){
         ZobrazCielLabel.setText(this.tura.getCiel());
        }
        if(this.tura.getTyp()!=null){
            ZobrazTypLabel.setText(this.tura.getTyp());
        }
        if(this.tura.getTrasa()!=null){
          ZobrazTrasaLabel.setText(this.tura.getTrasa());
         }
        if(this.tura.getPoznamky()!=null){
         ZobrazPoznámkylabel.setText(this.tura.getPoznamky());
        
        }
        if(this.tura.getDatum()!=null){
         ZobrazDatumLabel.setText(this.tura.getDatum().toString());
        }
        ZobrazHodnotenieLabel.setText(Integer.toString(this.tura.getHodnotenie()));
        
        if(this.tura.isPrejdene()){
         PrejdeneCheckBox.isSelected();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        upravitButton = new javax.swing.JButton();
        KrajinaLabel = new javax.swing.JLabel();
        ZobrazKrajinalabel = new javax.swing.JLabel();
        CielLabel = new javax.swing.JLabel();
        ZobrazCielLabel = new javax.swing.JLabel();
        DatumLabel = new javax.swing.JLabel();
        ZobrazDatumLabel = new javax.swing.JLabel();
        TypLabel = new javax.swing.JLabel();
        ZobrazTypLabel = new javax.swing.JLabel();
        TrasaLabel = new javax.swing.JLabel();
        ZobrazTrasaLabel = new javax.swing.JLabel();
        HodnotenieLabel = new javax.swing.JLabel();
        ZobrazHodnotenieLabel = new javax.swing.JLabel();
        PrejdeneCheckBox = new javax.swing.JCheckBox();
        PoznámkyLabel = new javax.swing.JLabel();
        ZobrazPoznámkylabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        upravitButton.setText("Upraviť");
        upravitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravitButtonActionPerformed(evt);
            }
        });

        KrajinaLabel.setText("Krajina:");

        ZobrazKrajinalabel.setText("nepoznačené");

        CielLabel.setText("Cieľ:");

        ZobrazCielLabel.setText("nepoznačené");

        DatumLabel.setText("Dátum:");

        ZobrazDatumLabel.setText("nepoznačené");

        TypLabel.setText("Typ:");

        ZobrazTypLabel.setText("nepoznačené");

        TrasaLabel.setText("Trasa:");

        ZobrazTrasaLabel.setText("nepoznačené");

        HodnotenieLabel.setText("Hodnotenie:");

        ZobrazHodnotenieLabel.setText("nepoznačené");

        PrejdeneCheckBox.setText("Prejdené");

        PoznámkyLabel.setText("Poznámky");

        ZobrazPoznámkylabel.setText("nepoznačené");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KrajinaLabel)
                            .addComponent(CielLabel)
                            .addComponent(DatumLabel)
                            .addComponent(TypLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZobrazKrajinalabel)
                            .addComponent(ZobrazCielLabel)
                            .addComponent(ZobrazDatumLabel)
                            .addComponent(ZobrazTypLabel)))
                    .addComponent(PrejdeneCheckBox))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addGap(18, 18, 18)
                        .addComponent(upravitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PoznámkyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(ZobrazPoznámkylabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(HodnotenieLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ZobrazHodnotenieLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TrasaLabel)
                            .addGap(35, 35, 35)
                            .addComponent(ZobrazTrasaLabel))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KrajinaLabel)
                    .addComponent(ZobrazKrajinalabel)
                    .addComponent(TrasaLabel)
                    .addComponent(ZobrazTrasaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CielLabel)
                    .addComponent(ZobrazCielLabel)
                    .addComponent(HodnotenieLabel)
                    .addComponent(ZobrazHodnotenieLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatumLabel)
                    .addComponent(ZobrazDatumLabel)
                    .addComponent(PoznámkyLabel)
                    .addComponent(ZobrazPoznámkylabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypLabel)
                    .addComponent(ZobrazTypLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrejdeneCheckBox)
                    .addComponent(okButton)
                    .addComponent(upravitButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
      setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void upravitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravitButtonActionPerformed
       UpravitTuristikaForm upravitTuristika = new UpravitTuristikaForm(this, true, tura);
       upravitTuristika.setVisible(true);
    }//GEN-LAST:event_upravitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZobrazitTuristika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CielLabel;
    private javax.swing.JLabel DatumLabel;
    private javax.swing.JLabel HodnotenieLabel;
    private javax.swing.JLabel KrajinaLabel;
    private javax.swing.JLabel PoznámkyLabel;
    private javax.swing.JCheckBox PrejdeneCheckBox;
    private javax.swing.JLabel TrasaLabel;
    private javax.swing.JLabel TypLabel;
    private javax.swing.JLabel ZobrazCielLabel;
    private javax.swing.JLabel ZobrazDatumLabel;
    private javax.swing.JLabel ZobrazHodnotenieLabel;
    private javax.swing.JLabel ZobrazKrajinalabel;
    private javax.swing.JLabel ZobrazPoznámkylabel;
    private javax.swing.JLabel ZobrazTrasaLabel;
    private javax.swing.JLabel ZobrazTypLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton upravitButton;
    // End of variables declaration//GEN-END:variables
}
