/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.traveltracker_paz1c;

import java.text.SimpleDateFormat;

/**
 *
 * @author Robert Link
 */
public class ZobrazitTuristikaForm extends javax.swing.JDialog {
   private Turistika tura = new Turistika();
   private SimpleDateFormat dateFormat = new SimpleDateFormat("d.M.yyyy");
    
    
    public ZobrazitTuristikaForm(javax.swing.JDialog parent , boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
      public ZobrazitTuristikaForm(javax.swing.JDialog parent , boolean modal,Turistika tura) {
       super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.tura=tura;
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KrajinaLabel = new javax.swing.JLabel();
        ZobrazKrajinalabel = new javax.swing.JLabel();
        CielLabel = new javax.swing.JLabel();
        ZobrazCielLabel = new javax.swing.JLabel();
        DatumLabel = new javax.swing.JLabel();
        ZobrazDatumLabel = new javax.swing.JLabel();
        TypLabel = new javax.swing.JLabel();
        ZobrazTypLabel = new javax.swing.JLabel();
        TrasaLabel = new javax.swing.JLabel();
        HodnotenieLabel = new javax.swing.JLabel();
        ZobrazTrasaLabel = new javax.swing.JLabel();
        ZobrazHodnotenieLabel = new javax.swing.JLabel();
        PoznámkyLabel = new javax.swing.JLabel();
        ZobrazPoznámkylabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        upravitButton = new javax.swing.JButton();
        PrejdeneLabel = new javax.swing.JLabel();
        ZobrazPrejdeneLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        KrajinaLabel.setText("Krajina:");

        ZobrazKrajinalabel.setText("nepoznačené");

        CielLabel.setText("Cieľ:");

        ZobrazCielLabel.setText("nepoznačené");

        DatumLabel.setText("Dátum:");

        ZobrazDatumLabel.setText("nepoznačené");

        TypLabel.setText("Typ:");

        ZobrazTypLabel.setText("nepoznačené");

        TrasaLabel.setText("Trasa:");

        HodnotenieLabel.setText("Hodnotenie:");

        ZobrazTrasaLabel.setText("nepoznačené");

        ZobrazHodnotenieLabel.setText("nepoznačené");

        PoznámkyLabel.setText("Poznámky");

        ZobrazPoznámkylabel.setText("nepoznačené");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        upravitButton.setText("Upraviť");
        upravitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravitButtonActionPerformed(evt);
            }
        });

        PrejdeneLabel.setText("Prejdené:");

        ZobrazPrejdeneLabel.setText("nie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KrajinaLabel)
                            .addComponent(CielLabel)
                            .addComponent(DatumLabel)
                            .addComponent(TypLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZobrazCielLabel)
                            .addComponent(ZobrazKrajinalabel)
                            .addComponent(ZobrazDatumLabel)
                            .addComponent(ZobrazTypLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrejdeneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ZobrazPrejdeneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HodnotenieLabel)
                            .addComponent(TrasaLabel)
                            .addComponent(PoznámkyLabel))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZobrazTrasaLabel)
                            .addComponent(ZobrazHodnotenieLabel)
                            .addComponent(ZobrazPoznámkylabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(upravitButton)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KrajinaLabel)
                    .addComponent(ZobrazKrajinalabel)
                    .addComponent(TrasaLabel)
                    .addComponent(ZobrazTrasaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HodnotenieLabel)
                    .addComponent(ZobrazHodnotenieLabel)
                    .addComponent(CielLabel)
                    .addComponent(ZobrazCielLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DatumLabel)
                    .addComponent(ZobrazDatumLabel)
                    .addComponent(PoznámkyLabel)
                    .addComponent(ZobrazPoznámkylabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypLabel)
                    .addComponent(ZobrazTypLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(okButton)
                        .addComponent(upravitButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PrejdeneLabel)
                        .addComponent(ZobrazPrejdeneLabel)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void upravitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravitButtonActionPerformed
        UpravitTuristikaForm upravit= new UpravitTuristikaForm(this, true, tura);
        upravit.setVisible(true);
        refresh();
    }//GEN-LAST:event_upravitButtonActionPerformed
    public void refresh(){
          if(this.tura.getKrajina()!=null){
         ZobrazKrajinalabel.setText(this.tura.getKrajina());
       }
        if(this.tura.getCiel()!=null){
         ZobrazCielLabel.setText(this.tura.getCiel());
        }
        if(this.tura.getTyp()!=null){
            ZobrazTypLabel.setText(this.tura.getTyp());
        }
        if(this.tura.getTrasa()!=null){
          ZobrazTrasaLabel.setText(this.tura.getTrasa());
         }
        if(this.tura.getPoznamky()!=null){
         ZobrazPoznámkylabel.setText(this.tura.getPoznamky());
        
        }
        if(this.tura.getDatum()!=null){
         ZobrazDatumLabel.setText(dateFormat.format(this.tura.getDatum()));
        }
        ZobrazHodnotenieLabel.setText(Integer.toString(this.tura.getHodnotenie()));
        
        if(this.tura.isPrejdene()){
         ZobrazPrejdeneLabel.setText("áno");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristikaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristikaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristikaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZobrazitTuristikaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZobrazitTuristikaForm dialog = new ZobrazitTuristikaForm(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CielLabel;
    private javax.swing.JLabel DatumLabel;
    private javax.swing.JLabel HodnotenieLabel;
    private javax.swing.JLabel KrajinaLabel;
    private javax.swing.JLabel PoznámkyLabel;
    private javax.swing.JLabel PrejdeneLabel;
    private javax.swing.JLabel TrasaLabel;
    private javax.swing.JLabel TypLabel;
    private javax.swing.JLabel ZobrazCielLabel;
    private javax.swing.JLabel ZobrazDatumLabel;
    private javax.swing.JLabel ZobrazHodnotenieLabel;
    private javax.swing.JLabel ZobrazKrajinalabel;
    private javax.swing.JLabel ZobrazPoznámkylabel;
    private javax.swing.JLabel ZobrazPrejdeneLabel;
    private javax.swing.JLabel ZobrazTrasaLabel;
    private javax.swing.JLabel ZobrazTypLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton upravitButton;
    // End of variables declaration//GEN-END:variables
}
