/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.traveltracker_paz1c;

/**
 *
 * @author Robert Link
 */
public class ZobrazitPodujatieForm extends javax.swing.JDialog {
    KulturnePodujatie kulturnePodujatie= new KulturnePodujatie();
    
    public ZobrazitPodujatieForm(javax.swing.JDialog parent , boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public ZobrazitPodujatieForm(javax.swing.JDialog parent , boolean modal,KulturnePodujatie kultPodujatie) {
         super(parent, modal);
            initComponents();
        kulturnePodujatie=kultPodujatie;
        
        if(kulturnePodujatie.getKrajina()!=null){
        ZobrazenakrajinaLabel.setText(kulturnePodujatie.getKrajina());
        }
        
        if(kulturnePodujatie.getMesto()!=null){
        ZobrazeneMestolabel.setText(kulturnePodujatie.getMesto());
        }
        
        if(kulturnePodujatie.getNazov()!=null){
        ZobrazenyNazovLabel.setText(kulturnePodujatie.getNazov());
        }
        
        if(kulturnePodujatie.getDatum() !=null){
        ZobrazenyDatumLabel.setText(kulturnePodujatie.getDatum().toString());
        }

        ZobrazeneHodnotenieLabel.setText(Integer.toString(kulturnePodujatie.getHodnotenie()));

        if(kulturnePodujatie.getLokalizacia()!=null){
        ZobrazeneMiestoLabel.setText(kulturnePodujatie.getLokalizacia());
        }

        ZobrazeneVstupneLabel.setText(Integer.toString(kulturnePodujatie.getVstupne()));

        if(kulturnePodujatie.getCasZaciatku() !=null){
        ZobrazenyCasLabel.setText(kulturnePodujatie.getCasZaciatku().toString());
        }
        
        if(kulturnePodujatie.getTyp()!=null){
        ZobrazenyTypLabel.setText(kulturnePodujatie.getTyp());
        }
        
        
        if(kulturnePodujatie.getPoznamky()!=null){
        ZobrazenePoznamkyLabel.setText(kulturnePodujatie.getPoznamky());
        }
        if(kulturnePodujatie.isNavstivene()){
        NavstiveneCheckBox.setSelected(true);
        }
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ZobrazeneMiestoLabel = new javax.swing.JLabel();
        KrajinaLabel = new javax.swing.JLabel();
        ZobrazenakrajinaLabel = new javax.swing.JLabel();
        MestoLabel = new javax.swing.JLabel();
        ZobrazeneMestolabel = new javax.swing.JLabel();
        NazovLabel = new javax.swing.JLabel();
        ZobrazenyNazovLabel = new javax.swing.JLabel();
        DatumLabel = new javax.swing.JLabel();
        ZobrazenyDatumLabel = new javax.swing.JLabel();
        HodnotenieLabel = new javax.swing.JLabel();
        ZobrazeneHodnotenieLabel = new javax.swing.JLabel();
        MiestoLabel = new javax.swing.JLabel();
        ZobrazeneMiestoLabel1 = new javax.swing.JLabel();
        casZaciatkuLabel = new javax.swing.JLabel();
        ZobrazenyCasLabel = new javax.swing.JLabel();
        VstupneLabel = new javax.swing.JLabel();
        ZobrazeneVstupneLabel = new javax.swing.JLabel();
        TypLabel = new javax.swing.JLabel();
        ZobrazenyTypLabel = new javax.swing.JLabel();
        PoznamkyLabel = new javax.swing.JLabel();
        ZobrazenePoznamkyLabel = new javax.swing.JLabel();
        NavstiveneCheckBox = new javax.swing.JCheckBox();
        OkButton = new javax.swing.JButton();
        UpravitButton = new javax.swing.JButton();

        ZobrazeneMiestoLabel.setText("nepoznačené");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        KrajinaLabel.setText("Krajina:");

        ZobrazenakrajinaLabel.setText("nepoznačené");

        MestoLabel.setText("Mesto:");

        ZobrazeneMestolabel.setText("nepoznačené");

        NazovLabel.setText("Názov:");

        ZobrazenyNazovLabel.setText("nepoznačené");

        DatumLabel.setText("Dátum:");

        ZobrazenyDatumLabel.setText("nepoznačené");

        HodnotenieLabel.setText("Hodnotenie:");

        ZobrazeneHodnotenieLabel.setText("nepoznačené");

        MiestoLabel.setText("Miesto:");

        ZobrazeneMiestoLabel1.setText("nepoznačené");

        casZaciatkuLabel.setText("Čas začiatku :");

        ZobrazenyCasLabel.setText("nepoznačené");

        VstupneLabel.setText("Vstupné:");

        ZobrazeneVstupneLabel.setText("nepoznačené");

        TypLabel.setText("Typ:");

        ZobrazenyTypLabel.setText("nepoznačené");

        PoznamkyLabel.setText("Poznámky:");

        ZobrazenePoznamkyLabel.setText("nepoznačené");

        NavstiveneCheckBox.setText("Navštívené");

        OkButton.setText("OK");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        UpravitButton.setText("Upraviť");
        UpravitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpravitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MestoLabel)
                            .addComponent(KrajinaLabel))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ZobrazenakrajinaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MiestoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ZobrazeneMestolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(casZaciatkuLabel)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ZobrazenyCasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(ZobrazeneMiestoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NavstiveneCheckBox)
                                .addGap(117, 117, 117)
                                .addComponent(OkButton)
                                .addGap(18, 18, 18)
                                .addComponent(UpravitButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HodnotenieLabel)
                                            .addComponent(DatumLabel)
                                            .addComponent(NazovLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ZobrazenyNazovLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                            .addComponent(ZobrazenyDatumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TypLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(VstupneLabel)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(ZobrazeneHodnotenieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PoznamkyLabel)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ZobrazenyTypLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(ZobrazeneVstupneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ZobrazenePoznamkyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MiestoLabel)
                            .addComponent(ZobrazeneMiestoLabel1)
                            .addComponent(ZobrazenakrajinaLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(KrajinaLabel)))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MestoLabel)
                    .addComponent(ZobrazeneMestolabel)
                    .addComponent(casZaciatkuLabel)
                    .addComponent(ZobrazenyCasLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NazovLabel)
                    .addComponent(ZobrazenyNazovLabel)
                    .addComponent(VstupneLabel)
                    .addComponent(ZobrazeneVstupneLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ZobrazenyTypLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DatumLabel)
                            .addComponent(ZobrazenyDatumLabel)
                            .addComponent(TypLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HodnotenieLabel)
                            .addComponent(ZobrazeneHodnotenieLabel)
                            .addComponent(PoznamkyLabel)
                            .addComponent(ZobrazenePoznamkyLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NavstiveneCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(OkButton)
                                    .addComponent(UpravitButton))))))
                .addGap(19, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_OkButtonActionPerformed

    private void UpravitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpravitButtonActionPerformed
        UpravitKultPodujatieForm kultura=new UpravitKultPodujatieForm(this, true,kulturnePodujatie);
        kultura.setVisible(true);
    }//GEN-LAST:event_UpravitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPodujatieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPodujatieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPodujatieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZobrazitPodujatieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ZobrazitPodujatieForm dialog = new ZobrazitPodujatieForm(new javax.swing.JDialog (), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DatumLabel;
    private javax.swing.JLabel HodnotenieLabel;
    private javax.swing.JLabel KrajinaLabel;
    private javax.swing.JLabel MestoLabel;
    private javax.swing.JLabel MiestoLabel;
    private javax.swing.JCheckBox NavstiveneCheckBox;
    private javax.swing.JLabel NazovLabel;
    private javax.swing.JButton OkButton;
    private javax.swing.JLabel PoznamkyLabel;
    private javax.swing.JLabel TypLabel;
    private javax.swing.JButton UpravitButton;
    private javax.swing.JLabel VstupneLabel;
    private javax.swing.JLabel ZobrazenakrajinaLabel;
    private javax.swing.JLabel ZobrazeneHodnotenieLabel;
    private javax.swing.JLabel ZobrazeneMestolabel;
    private javax.swing.JLabel ZobrazeneMiestoLabel;
    private javax.swing.JLabel ZobrazeneMiestoLabel1;
    private javax.swing.JLabel ZobrazenePoznamkyLabel;
    private javax.swing.JLabel ZobrazeneVstupneLabel;
    private javax.swing.JLabel ZobrazenyCasLabel;
    private javax.swing.JLabel ZobrazenyDatumLabel;
    private javax.swing.JLabel ZobrazenyNazovLabel;
    private javax.swing.JLabel ZobrazenyTypLabel;
    private javax.swing.JLabel casZaciatkuLabel;
    // End of variables declaration//GEN-END:variables
}
